package ch.cern.todo.exceptions;

public class TaskNotFoundException extends RuntimeException {

    private String errorMessage;

    public TaskNotFoundException(String errorMessage) {
        super(errorMessage);
        this.errorMessage = errorMessage;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}
